//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetDistributedClient.CreateImageServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Straight", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Straight : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AspNetDistributedClient.CreateImageServiceReference.Point FirstPointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AspNetDistributedClient.CreateImageServiceReference.Point SecondPointField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public AspNetDistributedClient.CreateImageServiceReference.Point FirstPoint {
            get {
                return this.FirstPointField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstPointField, value) != true)) {
                    this.FirstPointField = value;
                    this.RaisePropertyChanged("FirstPoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public AspNetDistributedClient.CreateImageServiceReference.Point SecondPoint {
            get {
                return this.SecondPointField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondPointField, value) != true)) {
                    this.SecondPointField = value;
                    this.RaisePropertyChanged("SecondPoint");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Point", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Point : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private float XField;
        
        private float YField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public float X {
            get {
                return this.XField;
            }
            set {
                if ((this.XField.Equals(value) != true)) {
                    this.XField = value;
                    this.RaisePropertyChanged("X");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public float Y {
            get {
                return this.YField;
            }
            set {
                if ((this.YField.Equals(value) != true)) {
                    this.YField = value;
                    this.RaisePropertyChanged("Y");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CreateImageServiceReference.CreateImageSoap")]
    public interface CreateImageSoap {
        
        // CODEGEN: Generating message contract since element name firstStraight from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        AspNetDistributedClient.CreateImageServiceReference.HelloWorldResponse HelloWorld(AspNetDistributedClient.CreateImageServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<AspNetDistributedClient.CreateImageServiceReference.HelloWorldResponse> HelloWorldAsync(AspNetDistributedClient.CreateImageServiceReference.HelloWorldRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public AspNetDistributedClient.CreateImageServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(AspNetDistributedClient.CreateImageServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AspNetDistributedClient.CreateImageServiceReference.Straight firstStraight;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public AspNetDistributedClient.CreateImageServiceReference.Straight secondStraight;
        
        public HelloWorldRequestBody() {
        }
        
        public HelloWorldRequestBody(AspNetDistributedClient.CreateImageServiceReference.Straight firstStraight, AspNetDistributedClient.CreateImageServiceReference.Straight secondStraight) {
            this.firstStraight = firstStraight;
            this.secondStraight = secondStraight;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public AspNetDistributedClient.CreateImageServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(AspNetDistributedClient.CreateImageServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(byte[] HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CreateImageSoapChannel : AspNetDistributedClient.CreateImageServiceReference.CreateImageSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateImageSoapClient : System.ServiceModel.ClientBase<AspNetDistributedClient.CreateImageServiceReference.CreateImageSoap>, AspNetDistributedClient.CreateImageServiceReference.CreateImageSoap {
        
        public CreateImageSoapClient() {
        }
        
        public CreateImageSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreateImageSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreateImageSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreateImageSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AspNetDistributedClient.CreateImageServiceReference.HelloWorldResponse AspNetDistributedClient.CreateImageServiceReference.CreateImageSoap.HelloWorld(AspNetDistributedClient.CreateImageServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public byte[] HelloWorld(AspNetDistributedClient.CreateImageServiceReference.Straight firstStraight, AspNetDistributedClient.CreateImageServiceReference.Straight secondStraight) {
            AspNetDistributedClient.CreateImageServiceReference.HelloWorldRequest inValue = new AspNetDistributedClient.CreateImageServiceReference.HelloWorldRequest();
            inValue.Body = new AspNetDistributedClient.CreateImageServiceReference.HelloWorldRequestBody();
            inValue.Body.firstStraight = firstStraight;
            inValue.Body.secondStraight = secondStraight;
            AspNetDistributedClient.CreateImageServiceReference.HelloWorldResponse retVal = ((AspNetDistributedClient.CreateImageServiceReference.CreateImageSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AspNetDistributedClient.CreateImageServiceReference.HelloWorldResponse> AspNetDistributedClient.CreateImageServiceReference.CreateImageSoap.HelloWorldAsync(AspNetDistributedClient.CreateImageServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<AspNetDistributedClient.CreateImageServiceReference.HelloWorldResponse> HelloWorldAsync(AspNetDistributedClient.CreateImageServiceReference.Straight firstStraight, AspNetDistributedClient.CreateImageServiceReference.Straight secondStraight) {
            AspNetDistributedClient.CreateImageServiceReference.HelloWorldRequest inValue = new AspNetDistributedClient.CreateImageServiceReference.HelloWorldRequest();
            inValue.Body = new AspNetDistributedClient.CreateImageServiceReference.HelloWorldRequestBody();
            inValue.Body.firstStraight = firstStraight;
            inValue.Body.secondStraight = secondStraight;
            return ((AspNetDistributedClient.CreateImageServiceReference.CreateImageSoap)(this)).HelloWorldAsync(inValue);
        }
    }
}
